### PR TITLE
added configuration spec for openstack cloud provider

### PR DESCRIPTION
**Pull request by mevansam**

### CODE REVIEW

**Comment by Manifaust** [comment]
@mevansam thank you for this PR. I'm asking the PM to prioritize this. I have some questions I was wondering if you could answer. Have you tested this yet with your openstack deployment? Which version of openstack did you use? Which version of keystone? And tenant/domain auth? (or both)

**Comment by mevansam** [comment]
I believe I ran the tests against Mitaka.

**Comment by glestaris** [comment]
Hey @mevansam, we added OpenStack cloud provider support in https://www.pivotaltracker.com/story/show/153816342 and we are going to look into this PR as part of https://www.pivotaltracker.com/story/show/154051296.

**Comment by BenChapman** [comment]
Hi,

Thanks for your pull request. This got completed in https://www.pivotaltracker.com/story/show/153816342. We're going to close this request! Feel free to reopen the issue if you have any further questions or suggestions.

Ben.

**Pull request closed without merging**
