### PR TITLE
kube-controller-manager: ca.pem remove new line

### PR DESCRIPTION
**Pull request by alekssaul**
Removes new line from the end of ca.pem file used by kube-controller-manager.

New line causes the secrets for service accounts to be generated with data/ca.crt having an additional new line. This causes issues with applications (ie: Spark on K8s) that use Java K8s client (`https://github.com/fabric8io/kubernetes-client`).

image

### CODE REVIEW

**Comment by alekssaul** [comment]
Hi, 
Part of Pivotal-Field-Engineering org, do I need to submit a CLA?

**Comment by BenChapman** [comment]
@alekssaul 

Thank you for the submission. You'll need to publicise your membership of that org as per the instructions of the bot:

> If you are confident that you're covered under a Corporate CLA, please make sure you've publicized your membership in the appropriate Github Org, per [these instructions](https://help.github.com/articles/publicizing-or-concealing-organization-membership/).

Thanks,
Ben.

**Comment by alekssaul** [comment]
Thanks @BenChapman , sorry I missed the org visibility, should be ok now.

**Comment by BenChapman** [comment]
Thank you for the pull request! We've merged this, and it should be available in the next version of CFCR.

**Pull request merged**
