### PR TITLE
Add to kubelet option to configure allow-privileged

### PR DESCRIPTION
**Pull request by shinji62**
Not sure is good to allow to true by default even if the apiserver is false.

This PR will put to false by default and add the options to setup to true.

I will send a PR to kubo-deployment too.

### CODE REVIEW

**Comment by shinji62** [comment]
@glestaris @tvs thanks

**Comment by glestaris** [comment]
same here, is this covered by https://www.pivotaltracker.com/story/show/153848167?

**Comment by shinji62** [comment]
Well I think as good practices kube-apiserver and Kubelet should be able to be set to false and not only one of them as it is now.

**Comment by akshaymankar** [comment]
@shinji62 As the story mentioned by @glestaris is delivered and accepted, I guess this PR is not needed to be merged. Thanks anyways for your contribution :)

I guess same applies for cloudfoundry-incubator/kubo-deployment#252

**Comment by shinji62** [comment]
Please check with Georges. I know the story get accepted but as explained I think that bad pratice to not disable container privileged on kubelet too. Doesn t make sens as least for me.

Envoyé de mon iPhone

**Pull request merged**
