### PR TITLE
Optionally disable creation of ingress rules on worker security groups

### PR DESCRIPTION
**Pull request by srbry**
Kubernetes amends the ingress rules on security groups bound to workers to allow access to ELBs.
This has scaling limits with number of rules allowed in a Security Group. If you set this you will need to make sure you open up your workers' security group from ELBs via another means.

This can also be used as workaround to bugs such as - https://github.com/kubernetes/kubernetes/issues/17626

### CODE REVIEW

**Comment by srbry** [comment]
The CLA should be signed now (I have publicised my membership of the Github org), does this need reopening?

**Comment by bsnchan** [comment]
Hey @srbry - we feel slightly hesitant about pulling this PR since this means that we will now need to support AWS cloud config.

Could you please update the PR to support all the AWS cloud config options as well?

**Comment by srbry** [comment]
@bsnchan I will have a look at adding the extra options.

**Comment by srbry** [comment]
@bsnchan what do you think of the new changes?

**Comment by Manifaust** [comment]
@glestaris the changes look alright. However, we'll need to update the cfcr manifest to support these new bosh properties and the deploy_k8s script to extract the properties from director.yml  (in kubo-deployment) and write the corresponding integration tests.

**Comment by glestaris** [comment]
Hey @srbry, sorry for dropping this for so long. Can you help me understand a bit more about the problem this is solving?

Did you hit a limit on the ingress rules K8s created? Did you encountered the issue described [in the K8s bug report](https://github.com/kubernetes/kubernetes/issues/17626) and had ELB take too long to delete?

**Comment by glestaris** [comment]
I don't think I understand this very well. What's the intention behind it? @cloudfoundry-incubator/cfcr-core do you think we should merge regardless?

I will close for now. Team, feel free to reopen. @srbry feel free to comment and tell me why we should merge :)

**Comment by iainsproat** [comment]
@glestaris I think the problem might be this:
https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_Limits.html#vpc-limits-security-groups
When you create a LoadBalancer Service via k8s, it creates a Security Group for that ELB and adds an ingress rule to the Security Group for the worker nodes.
I guess it's possible to hit the VPC limits if creating multiple loadbalancers though we haven't explicitly tested for this.
Relatedly, we noticed that when a k8s ELB is deleted, it fails to properly remove the ingress rules and security group it had created for that ELB.  We'd created a chore to workaround this on our CI environments: https://www.pivotaltracker.com/story/show/157113310

**Comment by srbry** [comment]
@glestaris A good reference to this issue seems to be: https://github.com/kubernetes/kubernetes/issues/26670

Basically, every time you expose a service using an LB Kubernetes will create a new ELB and append the rule to the instances security group.

Eventually, you will create enough ELBs that your security group hits the AWS limits and you will be unable to expose any new services. I think it will cap out at 250, so likely won't be an option for lots of people.

**Comment by srbry** [comment]
And what @iainsproat said 👍

**Comment by glestaris** [comment]
Thanks for the context @srbry / @iainsproat. Let's review this soon.

**Comment by alex-slynko** [comment]
Hey there @srbry 

Sorry for taking that long.
We have exposed all the properties from cloud provider. You can now pass it using the manifest. Feel free to add Pull Request to kubo-deployment with this properties.

**Pull request closed without merging**
