### PR TITLE
Azure Support (based on svrc-pivotal's pr). [use https://github.com/cloudfoundry-incubator/kubo-release/pull/223 instead, if  https://github.com/cloudfoundry/bosh-agent/pull/174 merged]

### PR DESCRIPTION
**Pull request by andyliuliming**

### CODE REVIEW

**Comment by alex-slynko** [comment]
Hi @andyliuliming 

Thank you for your pull request.
We had several questions for previous PR #191  
We documented it in our tracker. I'll copy that here for more visibility
https://www.pivotaltracker.com/story/show/155619338/comments/187957588

If you could answer these questions, we can merge it faster.
```
CIFS utils (for Windows/Azure files). We want to know if they are needed or if the PR's author was adding a feature
```
Do we need CIFS utils or can it be added later? (Then it can be tested separately)

```
* the PR adds logic as a workaround to the fact that Azure requires the vm ids to equal the hostname but the hostname is not resolvable by bosh-dns. We want to see if this works correctly and if it's necessary.
```
Do you know if this is necessary? Is it possible to override this? Is there a way to pass both instance ID and custom DNS name, and then resolve the node by custom DNS name? (this will help us with HTTP proxying). Node DNS aliases job was created to fix it, can we somehow get rid of it?

Additionally, could you please deploy this and make sure that conformance tests are passing. We got error with emptyDir test and we were not quite sure how to fix it.

Thank you again for the pull request, we will check it next week.

**Comment by andyliuliming** [comment]
Hi @alex-slynko ,
Thanks for the review.
The CIFS utils is not necessary for the PKS works in azure, but it add support for the azure file, and the azure file is used widely for the K8S customers in azure. so I think it's good to have the feature enabled at the same time. (https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-file)

and about the dns part, actually I have a better solution for this. I think this should be done in bosh-dns process, I think it's good for the bosh-dns can resolve the agent_id automatically.
 (I sent out a pr for this https://github.com/cloudfoundry/bosh-dns-release/pull/31)
also in this pr, one flag for switching the agent_id is provided.

Thanks

**Comment by andyliuliming** [comment]
@alex-slynko and the tempDir failure is due to the allow-previleged-container is not enabled. and also we should set disable_deny_escalating_exec to true to make the intra-pod and etc test pass at the same time.
here is one terraform to deploy:
https://github.com/virtualcloudfoundry/cf-azure-deployment/tree/dns_solution/cfcr

**Comment by andyliuliming** [comment]
@alex-slynko  have other PR without the dns workaround https://github.com/cloudfoundry-incubator/kubo-release/pull/223

but it depends on this pr https://github.com/cloudfoundry/bosh-agent/pull/174

**Comment by andyliuliming** [comment]
prefer https://github.com/cloudfoundry-incubator/kubo-release/pull/223 so close this pr.

**Pull request closed without merging**
