### PR TITLE
rename jobs/flannel -> jobs/flanneld to match job name

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by drnic** [comment]
I cannot see CI. What is the error? thx

**Comment by tvs** [comment]
Hi @drnic,

This change probably needs an corresponding change in [kubo-deployment](https://github.com/cloudfoundry-incubator/kubo-deployment). Unfortunately I'm not sure we have a good mechanism for pairing the two pull requests together into the test pipeline. This might require a more-manual approach to test.

**Comment by drnic** [comment]
@tvs no I don't think any changes necessary; BOSH is taking the `spec` `name` field; the directory name seems to be ignored. This PR just makes them all the same for improving human cognition.

**Comment by tvs** [comment]
My apologies, I mistook what the PR is doing. You're correct, there should be no need for an update to kubo-deployment. 

I think your original test run may have just hit at an unlucky time when the release or the test were horked (there's been a fair bit of churn on both lately). I've gone ahead and kicked off the tests and it's passing on gcp so far. The environments are a bit locked up at the moment, so it might be a awhile before it it goes through completely.

**Pull request merged**
