### PR TITLE
HTTP proxy support for cloud provider interactions

### PR DESCRIPTION
**Pull request by MatthiasWinzeler**
As discussed in #126

### CODE REVIEW

**Comment by glestaris** [comment]
hey @MatthiasWinzeler, sorry for dropping the ball on this.

Why is the `kubelet-password` property exposed?

**Comment by glestaris** [comment]
also, can we extend this to `https_proxy` for consistency with https://github.com/cloudfoundry-incubator/docker-boshrelease/blob/889931ecf134493ab4471fb3b9e482be3b628628/jobs/docker/spec#L127?

**Comment by MatthiasWinzeler** [comment]
@glestaris looks like `kubelet-password` came with this merge afterwards: https://github.com/cloudfoundry-incubator/kubo-release/pull/130/commits/45f41af7337ae335aa4fb9326b2585471787497c
It's not related to the PR and probably can be removed...

I think it's fine to also expose `https_proxy`. For us, it was not needed, since `http_proxy` also applies to https urls (golang's default behavior).

**Comment by glestaris** [comment]
:+1: thanks, we will look into merging this soon

**Comment by glestaris** [comment]
@MatthiasWinzeler the commits are merged. I am closing the PR.

**Comment by MatthiasWinzeler** [comment]
@glestaris great news, thank you!

**Comment by akshaymankar** [comment]
Thanks for your help with the no_proxy thing @MatthiasWinzeler

**Pull request closed without merging**
