### PR TITLE
change permission for product_serial

### PR DESCRIPTION
**Pull request by srm09**
- copy to kube-apiserver pre-start
- needed to address race condition where product_serial can't be read

[#154366287]

Signed-off-by: Sagar Muchhal <muchhals@vmware.com>

### CODE REVIEW

**Comment by srm09** [comment]
Raised this PR as part of the issue #161

**Comment by jfmyers9** [comment]
Hey @srm09 @Manifaust 

Can you give some more explanation around the motivation behind these changes? Specifically, can you explain the race condition surrounding `product_serial`?

Best,

@jfmyers9 && @iainsproat

**Comment by srm09** [comment]
@jfmyers9 && @iainsproat

While deploying CFCR on vSphere, the `kube-apiserver` job needs access to the `product_serial` file to determine the UUID for that specific VM. Here is the relevant piece of [code](https://github.com/kubernetes/kubernetes/blob/9befc2b8928a9426501d3bf62f72849d5cbcd5a3/pkg/cloudprovider/providers/vsphere/vsphere.go#L187).

In kubo-release, we change the permissions of this file in the `kube_controller_manager_ctl` startup script. Usually the startup script finishes before `kube-apiserver` reads the file. The race condition was discovered when we encountered a case where the `kube-controller-manager` job started after the `kube-apiserver` job which caused the permissions to not be set making the file unreadable. 

In the fix that @Manifaust and I made, we duplicated the permission change bit to the `pre-start` script of the `kube-apiserver` job. Thus, making sure that there is a hard requirement for the permissions on the product_serial file to be updated before it starts. This way we explicitly know that this job needs that file which was not very clear before.

**Comment by tvs** [comment]
Would it make more sense to change the file permissions as part of the `cloud-provider` job? The configuration of that file is part of setting up the necessary bits for the cloud provider to operate and it should make it so it's no longer duplicated across the two jobs.

`Cloud-provider` should already be configured to run before either the API server or Controller Manager (though it might be worth it to double-check) since it's a necessary component to the API server in the first place.

I don't recall if the job ordering enforces that `cloud-provider` runs first though

**Pull request merged**
