### PR TITLE
Allow configuring OpenID authentication

### PR DESCRIPTION
**Pull request by frodenas**
This PR adds support to configure the `apiserver` to use [OpenID Connect](https://kubernetes.io/docs/admin/authentication/#openid-connect-tokens). This will allow using Google, Azure AD or even CF UAA for user authentication.

### CODE REVIEW

**Comment by drnic** [comment]
Bump.

**Comment by bsnchan** [comment]
@glestaris This seems like a good thing to prioritize

**Comment by glestaris** [comment]
prioritised

**Comment by glestaris** [comment]
the commit has been merged https://github.com/cloudfoundry-incubator/kubo-release/commit/67bfa2279b1ac4961d3275fa313594a8b7c6470a

**Pull request closed without merging**
